# Generated by Django 4.0.4 on 2022-05-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(help_text='Ingrese el hobby', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre de la mascota', max_length=200)),
                ('tipo_de_mascota', models.CharField(help_text='Ingrese el tipo de mascota. P. ej: Gato, Perro', max_length=200)),
                ('raza', models.CharField(help_text='Ingrese la raza de la mascota', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_de_fallecimiento', models.DateField(blank=True, null=True)),
                ('hobby', models.ManyToManyField(help_text='Ingrese un hobby', to='miembros.hobby')),
                ('mascota', models.ManyToManyField(help_text='Ingrese la mascota', to='miembros.mascota')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
