# Generated by Django 4.0.4 on 2022-06-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={},
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='persona',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='hobby',
            field=models.ManyToManyField(blank=True, help_text='Seleccione el hobby de este familiar', null=True, to='miembros.hobby'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mascota',
            field=models.ManyToManyField(blank=True, help_text='Seleccione la mascota de este familiar', null=True, to='miembros.mascota'),
        ),
    ]
