# Generated by Django 4.0.4 on 2022-05-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='hobby',
            field=models.ManyToManyField(to='miembros.hobby'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mascota',
            field=models.ManyToManyField(to='miembros.mascota'),
        ),
    ]
