# Generated by Django 4.0.4 on 2022-06-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_alter_persona_hobby_alter_persona_mascota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={},
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='hobby',
            field=models.ManyToManyField(help_text='Seleccione el hobby de este familiar', to='miembros.hobby'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mascota',
            field=models.ManyToManyField(help_text='Seleccione la mascota de este familiar', to='miembros.mascota'),
        ),
    ]
