# Generated by Django 4.0.4 on 2022-06-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_alter_persona_options_rename_name_mascota_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
