# Generated by Django 4.0.4 on 2022-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0004_persona_correo_electronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='hobby',
            field=models.ManyToManyField(blank=True, help_text='Seleccione el hobby de este familiar', null=True, to='miembros.hobby'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mascota',
            field=models.ManyToManyField(blank=True, help_text='Seleccione la mascota de este familiar', null=True, to='miembros.mascota'),
        ),
    ]
